
exports.create_data = function create_data() {
  var DATA_LENGTH = 8000;
  var data = [];
  for (var i = 0; i < DATA_LENGTH; i++)
    data.push((i % 26) + 65);
  return data;
};


exports.create_text_old = function create_text_old() {
  var mystring = "hello bob!" + "\n";
  var addit = "how are you??" + "\n";
  mystring = mystring+mystring+addit+mystring+addit+addit+mystring+mystring+mystring+addit+mystring+mystring+mystring+mystring + "\0";
  var data = [];
  for (var i = 0; i < mystring.length; i++)
    data.push(mystring.charCodeAt(i));
  return data;
};


exports.create_text = function create_text() {
  var str = 
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sed massa ac tortor volutpat lacinia ut eget arcu. Cras sed metus ac massa consequat consectetur non eget libero. Suspendisse ut pharetra augue. Cras malesuada rhoncus nulla, ut ornare ex tincidunt et. Aenean semper convallis nunc sed scelerisque. Curabitur semper elit a ex dictum cursus. Suspendisse id mi dolor. Vivamus sed dictum mi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam diam elit, lacinia quis erat id, rutrum pulvinar justo. Etiam vestibulum urna purus, quis pulvinar erat condimentum sed. Fusce ac ullamcorper purus, non iaculis lectus. Sed quis orci dignissim, semper enim eu, finibus arcu." +
      "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec semper elementum nulla a dictum. Aliquam erat volutpat. Maecenas orci lacus, rutrum a mi sed, feugiat laoreet mauris. Cras pharetra condimentum ipsum, sed ornare nibh sagittis at. Fusce accumsan odio ante, at aliquet ex consectetur ac. Sed commodo eros egestas laoreet accumsan. Cras convallis mauris nec pharetra pharetra. Cras molestie dolor eros, in feugiat mauris scelerisque ut. Phasellus tincidunt porta elit, sit amet auctor velit maximus vel. Cras vel augue at erat facilisis fermentum at ac elit. Aenean nec quam dignissim, bibendum nibh at, fermentum turpis. Aliquam at nulla quis lorem mollis condimentum." +
      "Nunc consequat convallis nisi. Sed lobortis tortor non congue cursus. Vestibulum faucibus dapibus arcu, sit amet pretium arcu posuere aliquet. Aliquam erat volutpat. Proin ullamcorper ligula non eros congue, a fringilla risus ultrices. Phasellus elementum commodo elementum. Aliquam volutpat augue vitae eros dignissim aliquam. Praesent laoreet ante eget metus egestas, at consectetur ligula sagittis. Phasellus dapibus, nibh vel finibus commodo, ante nisl consectetur leo, hendrerit commodo arcu turpis ac tortor. Ut cursus vulputate nulla id efficitur. Praesent pharetra urna nec massa mattis, quis auctor arcu vehicula. Nulla dui ex, ultrices consequat lacus id, auctor placerat lacus." +
      "In feugiat sagittis arcu. Mauris porta interdum dolor at volutpat. Nam posuere magna et condimentum sodales. Integer augue ipsum, condimentum quis libero in, auctor finibus dui. Nulla bibendum fermentum blandit. Donec eget ipsum porta libero condimentum pulvinar. Sed tincidunt, justo vel sollicitudin porta, urna tortor venenatis enim, sed hendrerit neque tellus et nunc. Aenean mattis lorem dui, vel ultrices leo rhoncus quis. Morbi egestas imperdiet efficitur. Ut semper bibendum tincidunt. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus." +
      "Donec ac ipsum interdum, facilisis ipsum at, facilisis lorem. Sed tristique elit ut diam luctus ullamcorper. Nulla semper, libero vitae volutpat fermentum, arcu ligula consectetur urna, at gravida nibh purus vitae risus. Vivamus egestas, quam vel condimentum ornare, velit velit iaculis tellus, sit amet placerat erat elit eget dolor. Sed aliquam tellus ligula, in volutpat magna molestie ac. Nam erat turpis, tincidunt sed ex sit amet, interdum ullamcorper velit. Duis eget nisl sodales odio gravida congue sit amet eu neque. Suspendisse ac convallis felis. Aenean nec lorem eget lectus hendrerit ultrices suscipit at ante. Morbi placerat purus ut nunc finibus ultricies fermentum et sem." +
      "Aliquam lacus sapien, aliquam nec ipsum eu, porttitor pellentesque nunc. Etiam quis pulvinar dui. Cras mattis justo nec risus fermentum posuere. Nam eget dolor quis elit tincidunt volutpat. Fusce a velit dictum, pulvinar turpis et, finibus ante. Nam fringilla cursus lectus, vel hendrerit est tempor non. In hac habitasse platea dictumst. Donec non accumsan orci. Donec viverra eleifend metus, eget venenatis ante mollis eu. Donec eu nisl quis nulla laoreet maximus ut id augue. Proin elementum erat ornare, luctus sem eget, iaculis felis. Proin quis sapien non turpis finibus suscipit." +
      "Etiam vel egestas mauris. Proin sit amet felis sed justo euismod gravida. Morbi diam velit, tincidunt eget ipsum vel, tristique tincidunt neque. Cras non felis eget quam dictum euismod sed at enim. Vivamus aliquam libero sed enim euismod tincidunt. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus viverra enim id diam euismod, vitae condimentum tortor elementum. In in massa mattis, fermentum justo sit amet, faucibus turpis. In iaculis orci nec velit maximus, quis lobortis risus semper. Vestibulum sed aliquet velit, in finibus odio. Integer mi nibh, tempor vitae arcu eu, dictum consectetur lectus." +
      "Nulla eleifend dictum diam, condimentum gravida dolor bibendum in. Proin congue vitae augue eget volutpat. Duis aliquet vulputate vestibulum. Vivamus laoreet tortor purus, at venenatis nulla dictum vel. Curabitur hendrerit justo mauris, vitae eleifend nisi luctus eu. Integer eget rhoncus lacus, ut volutpat nisl. Donec id quam sed nulla viverra sollicitudin eget sit amet lacus. Vestibulum vitae nisl lectus. Aliquam erat volutpat. Nam rutrum odio sit amet molestie egestas. Fusce eu nunc dapibus, hendrerit ligula vel, eleifend lectus. Etiam felis nisi, vehicula quis porta sed, facilisis vel neque. Suspendisse vestibulum arcu consectetur ullamcorper imperdiet." +
      "Vestibulum id suscipit ipsum. Nullam sagittis metus felis, sit amet finibus diam euismod volutpat. Cras dictum turpis risus, laoreet cursus turpis vehicula elementum. Ut elementum odio eget mauris egestas, at blandit erat venenatis. Nam in volutpat leo, eu congue mauris. Mauris nec blandit magna. Sed semper lorem eget erat condimentum tempor. Cras eu ligula imperdiet metus commodo interdum at eu lectus. Praesent vitae odio eget tellus tincidunt tincidunt quis et arcu. Nulla dictum imperdiet posuere. Pellentesque pharetra mauris euismod est congue, vitae vulputate purus lobortis. Nunc at elit non orci facilisis porta. Fusce vitae volutpat nunc, ac bibendum libero. Pellentesque gravida orci at massa imperdiet, at condimentum libero facilisis. Curabitur tempor dolor ac varius iaculis. Morbi a metus lectus." +
      "Suspendisse sollicitudin rutrum urna ac vulputate. Vivamus bibendum mattis rhoncus. Cras sit amet tincidunt sem. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus consectetur semper magna, fringilla egestas sapien pellentesque pharetra. Suspendisse ac nibh ante. Integer eu vestibulum elit, et interdum augue. Integer commodo velit quis risus accumsan efficitur. Sed hendrerit iaculis risus quis elementum. Phasellus elementum in dolor et tincidunt. Suspendisse nec pulvinar ante. Donec ac neque id turpis accumsan ultricies eleifend quis sem. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel molestie dolor." +
      "Morbi eget ex nec odio cursus sollicitudin eu eget nibh. Donec in tortor et velit tempor euismod. Quisque condimentum elit dolor, ut posuere nunc facilisis sit amet. Vivamus dui ante, ultricies a ullamcorper vitae, sodales ultricies diam. Nunc a sem sollicitudin, cursus nisi rhoncus, consequat nibh. Phasellus iaculis odio sed odio fringilla, at vestibulum nibh scelerisque. Aliquam aliquet congue faucibus. Pellentesque posuere faucibus nisi et gravida." +
      "Nullam maximus viverra fermentum. Curabitur id lobortis risus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce tincidunt convallis purus, non commodo purus fermentum in. Ut auctor eleifend enim, sed posuere tellus iaculis a. Suspendisse ut enim eget odio vulputate fringilla. Proin malesuada sagittis efficitur. Ut tincidunt venenatis lacus sagittis faucibus. Sed ultricies turpis diam, sed dignissim eros ornare eu. Curabitur sem orci, commodo in congue at, tincidunt non enim. Vivamus consequat eu arcu id molestie." +
      "Aliquam ac fringilla odio, ac congue augue. Suspendisse maximus, urna a sagittis pharetra, risus leo eleifend dui, a finibus tortor felis ut erat. Curabitur condimentum metus sapien, et fermentum arcu dignissim eget. Etiam ut sapien elementum, dignissim est in, maximus lacus. Mauris fermentum, velit quis molestie vehicula, massa purus lobortis metus, in efficitur massa justo sit amet leo. Morbi porttitor, erat in dignissim vulputate, elit risus tincidunt tellus, vel lobortis arcu velit non odio. Ut tincidunt fringilla quam, vitae egestas sem sollicitudin et. Morbi bibendum eu dui nec egestas. Sed consectetur gravida tortor nec bibendum. Aliquam erat volutpat. Phasellus ante orci, tempor ut nunc et, vestibulum efficitur arcu. Nulla commodo eu sapien ac viverra. Nullam eget magna libero. Praesent in suscipit lectus, sed euismod massa. Curabitur efficitur lectus vel scelerisque efficitur." +
      "Donec ligula diam, vulputate in aliquam non, posuere in massa. Nullam fringilla nibh in leo accumsan, at tincidunt ante egestas. Vivamus dui elit, suscipit et elementum id, tempor et ex. Cras nec ultrices felis, a dapibus enim. Quisque hendrerit bibendum imperdiet. Etiam ligula mi, egestas eget mi eget, pretium interdum neque. Nullam molestie lorem in lobortis congue. Duis semper nunc sollicitudin scelerisque ornare. Etiam sit amet mauris est." +
      "Donec nisi lectus, mollis vitae ante non, elementum molestie nibh. Mauris hendrerit tincidunt eros eget pharetra. Morbi rutrum, purus non imperdiet iaculis, eros risus hendrerit libero, vitae accumsan orci velit ac leo. Pellentesque eget euismod massa. Proin vehicula mauris et nunc tempus, vel blandit ipsum mattis. Praesent id interdum ex. Quisque euismod sollicitudin eros." +
      "Sed laoreet purus eu lacinia dictum. Aliquam ac ligula id quam porta iaculis in et est. Maecenas pharetra metus quis velit lacinia luctus. Quisque condimentum ipsum orci, sed bibendum libero eleifend at. Duis fringilla purus non orci sollicitudin, eu mattis augue congue. Nulla et nunc mollis, ultricies est eget, pretium urna. Aenean tristique felis quis condimentum gravida. Duis ac congue metus. Aenean tristique est eget tortor viverra ultricies. Phasellus ac arcu pharetra, suscipit purus nec, volutpat erat." +
      "Mauris gravida tincidunt mi, sit amet sollicitudin turpis maximus ut. Proin tincidunt accumsan ipsum et sodales. Praesent risus nunc, consequat vitae magna nec, venenatis gravida risus. Vestibulum dolor nulla, tristique et vehicula ac, laoreet vel tellus. Duis fermentum interdum scelerisque. Donec vestibulum purus sed eleifend viverra. Ut scelerisque aliquet nisl, in lacinia odio dignissim vel. Fusce turpis diam, mollis non aliquet vel, consequat non massa. Morbi varius metus sit amet dignissim posuere. Donec interdum purus lectus, non tincidunt leo vestibulum vitae. Curabitur eu eros dapibus, porta lectus a, suscipit orci. Aliquam suscipit suscipit sapien, non ultricies ex tincidunt in. Nam aliquet neque id augue tempor egestas. Nulla non lacus ante. Integer sodales porta pellentesque." +
      "Sed lectus mauris, elementum blandit malesuada in, tincidunt sit amet sem. Sed consectetur maximus consequat. Nullam ut felis massa. Donec ut lacus tincidunt, pharetra magna aliquet, sodales tortor. Curabitur sagittis libero a venenatis volutpat. Nullam tortor nisl, consequat ac nunc sit amet, scelerisque finibus arcu. Quisque vel elit eget lorem placerat ultricies a quis eros. Donec eget porttitor ex. Aenean ut erat rhoncus, pellentesque turpis ut, varius ligula. Etiam vestibulum hendrerit lobortis. Duis at tortor imperdiet, elementum ligula et, pharetra ante." +
      "Nullam malesuada tincidunt ligula. Etiam ac ante tellus. Nunc molestie, ligula sit amet fringilla hendrerit, lectus ex auctor sem, sed facilisis diam sem non diam. In ut ante a ex posuere interdum. Suspendisse non vestibulum magna, ut feugiat risus. Nulla facilisi. Praesent rhoncus quis magna quis lacinia. Morbi enim tortor, hendrerit at pellentesque eget, egestas et tellus. Duis ut turpis ante. In quis pulvinar tellus. In id mollis metus, sed porttitor ligula. Quisque eu ligula nec tortor laoreet ornare ac in velit. Integer nec massa ut augue egestas laoreet et in ligula. Fusce scelerisque, purus in sodales tristique, urna lacus placerat mi, ac tincidunt dolor dui eget libero. Morbi consequat finibus lectus, ac congue augue blandit quis." +
      "Pellentesque bibendum a sapien at egestas. In semper, magna sed tincidunt ultrices, justo sapien feugiat turpis, et aliquam turpis elit tincidunt orci. Mauris elementum sollicitudin augue, viverra placerat neque porta eget. Ut magna ante, consequat finibus massa eu, ornare aliquet turpis. Nunc semper mauris in est elementum dignissim. Aenean quis gravida felis. Praesent urna mauris, tristique at iaculis lobortis, euismod vel nisl. Maecenas libero ligula, pellentesque non nisl sed, varius congue risus. Quisque elementum porta quam, quis sodales metus lacinia eget. Morbi ultrices mi erat, consequat dapibus est eleifend at. Praesent hendrerit facilisis ante, a congue arcu ultrices sit amet. Suspendisse potenti. Integer aliquam diam quis laoreet sodales." +
      "Nulla facilisi. Morbi tincidunt erat non sagittis vulputate. Nullam ut elit sed ligula condimentum pellentesque sit amet ut quam. Sed vitae purus posuere, sodales ligula ut, interdum ante. Aliquam ut molestie justo, viverra consectetur odio. Phasellus et ultrices augue, non ultricies nulla. Proin aliquam ultricies purus in tristique. Suspendisse laoreet massa vitae pretium viverra. Donec vel fermentum ante. Morbi at pharetra est. Fusce sit amet ultricies sapien. Nunc quis arcu in lacus tincidunt accumsan." +
      "Maecenas ac sapien lectus. Proin ultricies, nunc eu dignissim mattis, tellus turpis condimentum justo, id accumsan justo tortor in ex. Morbi euismod dolor leo, at posuere diam ultrices a. Donec rhoncus porttitor metus ut molestie. Aliquam commodo, magna eu placerat tempus, tortor leo tempus dolor, et imperdiet neque leo quis purus. Suspendisse laoreet interdum pretium. Nullam accumsan velit sit amet arcu convallis imperdiet. Integer venenatis fringilla felis. Nulla eu neque a sem viverra laoreet. Nam consequat tellus eu lacus ullamcorper sodales. Quisque volutpat dapibus lorem viverra consectetur. Sed vitae ornare diam, in viverra orci. Cras tincidunt at enim tempor pretium. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas." +
      "Duis nec tortor libero. Aliquam mollis est dui, at eleifend odio commodo at. Nunc et lacinia justo. Vestibulum in tortor velit. Sed enim nunc, luctus eu sem vel, cursus malesuada ante. Nulla laoreet libero ac est interdum auctor. Nunc vehicula vel libero non facilisis. Nulla tempor sodales mauris, sit amet condimentum odio porttitor ut. Integer suscipit leo sit amet elit volutpat, at posuere elit commodo. Morbi at purus porttitor, aliquam neque ut, congue nisl. Phasellus rhoncus ipsum justo, vitae dapibus nibh bibendum id. Quisque luctus purus diam. Nulla vehicula porta libero, vitae pharetra urna porttitor eu." +
      "Nullam mattis augue a nisi sollicitudin, eget eleifend velit lobortis. Phasellus hendrerit sem tortor, sed venenatis enim sollicitudin nec. Vivamus gravida ullamcorper enim et ultrices. Vestibulum lacus erat, ullamcorper nec nunc non, semper auctor nulla. Proin ut condimentum sem, nec semper nulla. Ut at dapibus metus. Sed vitae tempor turpis, at porta libero. Morbi sed egestas nulla, sed congue odio. Nulla porttitor quam at lectus suscipit bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec laoreet ligula eget nulla consequat, id congue elit varius. Phasellus eget tellus at odio consequat tempor a eget leo. Suspendisse sollicitudin dictum metus in consequat." +
      "Aenean faucibus augue a ipsum dapibus blandit. Sed justo metus, euismod vel sapien a, tincidunt molestie velit. Mauris pulvinar pulvinar ante ut auctor. Praesent quis turpis tristique, lobortis nibh sed, consectetur elit. Pellentesque lorem leo, volutpat a purus vitae, accumsan efficitur quam. Maecenas sit amet pretium leo, tincidunt gravida purus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec fermentum neque sit amet elit scelerisque tempus. Donec ullamcorper mollis augue, eu hendrerit mauris." +
      "Proin neque ante, iaculis eget purus in, pulvinar bibendum lorem. Mauris efficitur dui risus, eu fringilla neque rhoncus sit amet. Donec interdum sem sit amet nisl fermentum vestibulum. Nulla ullamcorper vestibulum feugiat. Nam eu pretium lectus, eu dignissim est. Phasellus in ligula dapibus, condimentum libero ut, sollicitudin quam. Sed faucibus dolor a dui condimentum dapibus. Pellentesque euismod sed arcu viverra malesuada. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut sit amet dapibus odio, sed mattis tortor. Proin in odio nibh. Quisque commodo nisl in ex pulvinar, a consequat libero pulvinar." +
      "Ut vestibulum sapien felis, et efficitur lorem porta ut. Phasellus sodales aliquet sem, ut accumsan massa lobortis nec. Quisque quis turpis in mauris luctus consequat non at justo. Pellentesque pulvinar justo vel ex aliquam placerat. Quisque fermentum id tortor a volutpat. Nullam a elementum eros, quis eleifend mi. Sed mi lorem, congue vitae mollis id, euismod sit amet quam. Aenean at diam in lacus elementum suscipit vitae sodales orci. Nulla pellentesque turpis nulla, ac scelerisque nibh iaculis sed. Duis dignissim sem dolor, ac condimentum justo aliquam eu. Suspendisse eu finibus ex. Donec mollis id nulla a bibendum. Fusce vitae quam leo." +
      "Suspendisse at ornare magna. Pellentesque sagittis mauris ut interdum cursus. Vivamus sit amet elementum metus, ut malesuada erat. Phasellus pellentesque, odio id luctus tempus, libero leo fringilla arcu, id bibendum nisl nulla non eros. Vivamus in libero iaculis magna accumsan semper et ac dui. In sit amet urna molestie, ornare mauris eget, imperdiet nulla. Sed eu ipsum eu sapien placerat tristique nec in leo. Nullam luctus enim massa, at pellentesque dui luctus id. Nullam non lacus non risus sagittis scelerisque at nec ligula. Mauris hendrerit mauris sed convallis tincidunt. Nam id felis blandit, mollis nibh nec, tincidunt augue. Suspendisse venenatis, tortor quis lacinia facilisis, neque lectus ornare magna, ornare accumsan metus leo quis mi. In eleifend tortor sed eleifend tristique." +
      "Duis eu dolor at augue iaculis tincidunt eget nec lectus. Suspendisse sagittis iaculis lacinia. Aliquam purus dui, rhoncus vitae tortor sed, porta fringilla neque. Mauris non auctor sem. Suspendisse diam dolor, interdum ac eros sed, viverra euismod sapien. In semper laoreet consectetur. Suspendisse ullamcorper consectetur metus, maximus interdum urna consequat at. Donec ultrices mi nec velit semper convallis. Vestibulum sit amet consectetur arcu. In volutpat lacus eget efficitur facilisis. Duis ullamcorper in massa ac laoreet. Sed aliquam lorem lorem, vel consequat neque faucibus nec." +
      "Vestibulum feugiat ipsum vel cursus porta. Praesent ut nulla placerat, mollis dolor tempus, dapibus tellus. Pellentesque elit justo, ultrices ut nibh quis, gravida rhoncus arcu. Fusce ut vehicula elit. Aliquam iaculis augue ac diam mollis, non sodales libero dictum. Nullam a ipsum at eros aliquet tempus ut eget lorem. Phasellus ac blandit dui. Cras justo tellus, finibus vitae auctor et, volutpat vel libero. Vestibulum orci urna, semper eget tincidunt ut, interdum vitae ipsum. Phasellus finibus pellentesque nibh, sit amet blandit tellus lacinia sed. Suspendisse dapibus leo orci, a dapibus ligula molestie non. Mauris non luctus felis, lobortis congue ligula. Integer nec vestibulum dui. Morbi rhoncus sem tincidunt, hendrerit urna ac, pharetra orci. Suspendisse pellentesque, lorem id interdum pulvinar, ex erat pharetra justo, tempus vestibulum velit ex et metus. Cras mattis, risus non tempus aliquam, nunc erat dictum eros, quis dapibus mi quam id leo." +
      "Sed sapien lacus, tincidunt vitae arcu sed, dignissim vulputate lacus. Morbi congue convallis ipsum, id fermentum nunc facilisis sed. Nulla lacus tortor, volutpat vel semper at, aliquet ac diam. Quisque facilisis, lectus ac fermentum facilisis, ipsum tellus venenatis diam, vel cursus dui dui vel diam. Sed blandit venenatis diam, eget ullamcorper enim pulvinar nec. Fusce sit amet mi eu quam tristique pretium molestie eget felis. Proin hendrerit libero nisl, vel tempus nunc convallis ut. Ut nibh ante, convallis sed orci quis, euismod sollicitudin magna." +
      "Integer sed blandit risus. In hac habitasse platea dictumst. Nam faucibus turpis at ligula dapibus, vitae tempus nibh iaculis. Aenean a mauris eu massa bibendum commodo sit amet et leo. Aliquam sollicitudin bibendum sem, tempus eleifend ex feugiat vel. Duis finibus vel urna quis luctus. Curabitur diam turpis, tincidunt sit amet metus id, ullamcorper rutrum diam. Curabitur volutpat felis est, sit amet pellentesque dolor fringilla eget. Etiam egestas gravida lectus ut pulvinar. Curabitur condimentum lorem dolor, tempor pellentesque justo fringilla vitae. Nam placerat velit at aliquet egestas. Maecenas ut ipsum sed turpis commodo aliquam in ut quam. Pellentesque vulputate mauris et libero ultricies consectetur. Nunc nec faucibus ex." +
      "Donec quis condimentum metus, vitae feugiat orci. Nullam id tempor ipsum. Nulla laoreet purus id lacinia laoreet. Suspendisse pharetra, turpis ultricies dignissim posuere, risus dui imperdiet est, nec consectetur tortor justo vel arcu. Nulla et dignissim libero. Cras eget imperdiet purus. Nullam eleifend pretium lacus in congue. Phasellus mi lorem, posuere ut mattis sit amet, molestie suscipit urna. Quisque ut arcu nec sem dignissim imperdiet. Ut dignissim vitae risus sit amet rutrum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec diam aliquam, semper arcu eu, pretium ex. Donec accumsan justo massa, sit amet volutpat ligula rutrum ut. Donec at urna vitae odio pellentesque lacinia non et odio. Etiam nec erat vitae risus ullamcorper laoreet." +
      "Aenean quis accumsan nisl. Vestibulum ligula diam, dignissim vitae accumsan non, mattis eu arcu. Donec gravida tortor vitae lacus scelerisque, at rutrum nibh euismod. Suspendisse a commodo purus, ac elementum elit. Sed molestie magna sed libero cursus laoreet sed sit amet ante. Aenean venenatis neque a justo fermentum, tristique venenatis libero cursus. Donec luctus nulla vitae luctus venenatis. Maecenas quis libero risus. Fusce metus ex, rhoncus ut ante ac, semper scelerisque augue. Morbi id consequat eros. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin at erat posuere, ullamcorper nibh eget, volutpat leo." +
      "Suspendisse fringilla commodo erat, nec sollicitudin orci egestas eu. Fusce congue condimentum suscipit. Sed maximus odio mi, placerat luctus magna scelerisque in. Donec at risus sem. Aliquam hendrerit nulla sed dapibus faucibus. Integer dignissim ex at risus feugiat, vel ultrices velit bibendum. Nulla dictum sem lorem, pretium egestas enim malesuada ut. Nam blandit nibh vitae ipsum euismod volutpat. Curabitur in consequat leo. Vivamus et massa in risus euismod cursus quis a tellus. Sed bibendum ut quam non blandit." +
      "Mauris malesuada id diam et lobortis. Donec malesuada sodales sem. Donec lobortis justo risus, vel tempus nunc accumsan eget. Nam mollis rutrum sodales. Etiam non quam mollis, fermentum tortor nec, placerat sapien. Sed ac dolor sagittis, volutpat libero sit amet, pharetra turpis. Cras in orci nec ipsum dignissim sollicitudin. Cras vel egestas mauris. Praesent facilisis dui erat, eget viverra velit venenatis et. Sed porta neque vel turpis euismod, et condimentum tellus sagittis. Sed a sapien quis metus sagittis porta vitae sit amet leo. Aliquam vel mi id leo dictum dapibus." +
      "Fusce tincidunt tempor mauris, faucibus scelerisque ex malesuada sed. Mauris sagittis tincidunt ligula, ac pulvinar nunc rutrum non. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec rutrum quis elit vel vulputate. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vel congue leo, at scelerisque ante. Mauris porttitor interdum venenatis. Vestibulum auctor arcu lectus, non pretium enim ultricies vel. Phasellus mattis ultrices nunc, ac pharetra urna volutpat id. Sed quis convallis ipsum. Proin feugiat libero nisl, sit amet imperdiet ante feugiat eget. Aenean mauris nibh, viverra id scelerisque a, aliquam sit amet erat. Aenean aliquet magna eu lobortis egestas. Aenean vehicula risus ac turpis fringilla vestibulum. Vivamus porttitor ligula sed ex cursus scelerisque." +
      "Nam eget fringilla est. Donec tempor metus sed arcu feugiat, quis vestibulum nulla laoreet. Sed vitae luctus metus. Curabitur id auctor justo, nec eleifend tellus. Mauris interdum sagittis sapien, in porta elit. Aliquam erat volutpat. Praesent dictum efficitur leo a fermentum. Nulla consectetur non massa cursus finibus. Duis convallis imperdiet dignissim. Aenean blandit est sem, vel pharetra nunc maximus non. Morbi malesuada, sem sit amet blandit suscipit, est nisi semper leo, eget rutrum lorem orci sit amet sapien. Aenean auctor gravida aliquam. Duis aliquet velit eget urna fringilla placerat." +
      "Morbi tempor, erat rutrum tincidunt sagittis, leo nibh feugiat lacus, non suscipit magna enim sed nisl. Mauris eleifend dolor libero, sit amet sodales odio tincidunt at. Integer maximus vulputate egestas. Phasellus tortor nulla, laoreet nec finibus viverra, commodo ut ex. Suspendisse ex lacus, porttitor in risus quis, congue ultrices neque. Donec iaculis purus sapien, vitae pellentesque urna scelerisque et. Cras egestas odio eget erat consectetur, nec bibendum risus lobortis. Morbi at porta nunc. Suspendisse potenti." +
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam facilisis lectus id dui malesuada, id dictum enim tristique. Morbi aliquam nunc sem, in iaculis enim hendrerit ultricies. Vestibulum at enim accumsan ipsum condimentum congue. Curabitur sollicitudin tortor ut tortor molestie dapibus. Curabitur ultricies vulputate tempus. Cras vestibulum quam eleifend, porttitor odio eget, faucibus nisi. Ut efficitur egestas ex." +
      "Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce est felis, fermentum vitae posuere sed, ullamcorper ut quam. Aenean nec sapien sed nibh sodales gravida et vel est. Quisque quis est varius, cursus felis id, aliquam dolor. Nam commodo erat sem, sit amet porta ante iaculis at. Integer a nunc imperdiet, venenatis neque sollicitudin, volutpat massa. Curabitur porta, metus vitae commodo sodales, justo diam eleifend justo, at molestie quam libero a lectus. Mauris neque lorem, placerat et elementum vitae, accumsan interdum elit." +
      "Mauris scelerisque nulla et tempor cursus. Donec luctus pharetra tellus. Suspendisse auctor interdum turpis id dictum. Duis scelerisque ligula ligula, in condimentum est dignissim at. Proin faucibus enim laoreet, dignissim elit id, dictum ex. Aliquam erat volutpat. Pellentesque magna quam, consectetur at est quis, egestas vehicula ante. Donec imperdiet sem in tellus pellentesque, nec bibendum est tempor. Nunc tristique sollicitudin efficitur. Vivamus semper ligula et justo aliquet porta. Nulla viverra eget neque vel pretium. Integer lacinia, nunc a iaculis semper, metus ante suscipit diam, sit amet pretium dui ligula vitae dolor. Aliquam dapibus elementum velit, a auctor purus tempus ut. Donec dignissim justo urna, et tempor tellus condimentum iaculis. Fusce congue gravida ex, eu pellentesque felis. Curabitur non massa ac tortor posuere rutrum at sodales est." +
      "Curabitur dapibus magna id enim rutrum efficitur. Maecenas nibh augue, mattis iaculis placerat sit amet, aliquam vel leo. Morbi metus purus, malesuada nec risus in, elementum tempor augue. Donec hendrerit nisi et velit placerat porttitor. Phasellus non quam tellus. Praesent consectetur, augue hendrerit ornare fermentum, risus justo dignissim arcu, a scelerisque nisl massa sed arcu. Pellentesque pulvinar eros volutpat mauris pretium, vitae ullamcorper magna suscipit. Phasellus mollis tristique ex sed tempus. Nunc erat neque, aliquet sed ex eu, dictum ornare lacus. Morbi ut metus aliquet, condimentum dui et, dictum nibh. Quisque ut imperdiet nulla. Nullam laoreet pellentesque lorem, vitae fermentum neque porttitor quis. Morbi venenatis hendrerit massa vel egestas." +
      "Nam posuere pretium massa, ac tristique neque varius tincidunt. Proin auctor ex vel mattis sollicitudin. Suspendisse ut fringilla augue. Ut laoreet iaculis orci, eget gravida nunc venenatis et. Fusce non dignissim eros. Donec risus arcu, consectetur sit amet sodales dignissim, lobortis vel mauris. Suspendisse semper justo sed orci consectetur, sit amet placerat mi sodales. Aliquam at ligula id velit ornare dignissim." +
      "Nam in ipsum vitae purus bibendum placerat quis a turpis. Aliquam commodo in nunc ut eleifend. Ut sit amet dolor vitae est tempor bibendum. Integer facilisis tortor vel lorem tristique, egestas blandit arcu placerat. Mauris ornare accumsan orci, id hendrerit nunc consequat ac. Vivamus ullamcorper, felis vitae dignissim feugiat, augue lorem auctor magna, at ultricies augue libero vel elit. Donec lacus ligula, tincidunt vitae dignissim a, sagittis quis sem. Suspendisse ac tellus dui. Nunc vestibulum libero vel lorem efficitur, in iaculis massa dignissim. Vestibulum id justo vel dolor mollis sagittis. Donec tincidunt metus vitae metus luctus fringilla." +
      "Donec in sagittis enim. Praesent lacinia lacus vitae orci pharetra sodales. Ut consequat est a ipsum feugiat hendrerit. Integer purus lorem, congue eu posuere placerat, dapibus in ipsum. Ut semper, dui vel tincidunt maximus, leo velit ullamcorper sem, quis vulputate ipsum dui ut nisl. Morbi tellus orci, ultrices eget tincidunt ac, mollis sit amet velit. Suspendisse commodo ligula a elit dictum maximus. Aenean volutpat rutrum quam vel viverra. Vestibulum eleifend, ligula in gravida posuere, ipsum libero semper est, vitae porta massa magna eu odio. Mauris mollis neque et elit faucibus, id dapibus metus viverra. In congue aliquam augue, in tincidunt ligula molestie eu. Suspendisse potenti. Duis congue vehicula felis, in dapibus enim faucibus ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas." +
      "Morbi semper pharetra sapien, sed sagittis lacus ultrices non. Duis vitae euismod purus. Vivamus dapibus eu eros non viverra. Donec velit diam, blandit at egestas eget, rutrum condimentum massa. Aliquam eget purus ut ligula tempus luctus. Quisque commodo rhoncus dui, vitae vulputate lectus ullamcorper eu. Proin quis venenatis velit, ut consectetur massa. Nunc volutpat, est in bibendum mattis, magna sem suscipit enim, eu varius nibh massa non turpis. Nullam euismod diam a est convallis semper. Duis eu libero fermentum, efficitur tortor sit amet, eleifend risus." +
      "Sed vulputate sed justo sit amet viverra. Morbi tempor finibus nisi eu bibendum. Curabitur consequat eu elit sed dignissim. Morbi libero sem, ultrices a cursus sit amet, imperdiet ut massa. Cras viverra nisi eros, at auctor diam porttitor molestie. Fusce mattis diam et urna facilisis, ut volutpat metus ullamcorper. Duis dignissim mauris ac nulla volutpat consectetur. In a ornare mi, non dapibus ipsum. Ut a lacus nec lacus commodo ornare a nec tortor. Nullam iaculis molestie semper. Ut dapibus mollis mauris, quis porta quam luctus quis." +
      "Maecenas molestie tortor non lorem mollis porta. Suspendisse sit amet lectus porttitor, pretium velit sed, accumsan eros. Suspendisse at sagittis arcu. In in pharetra tellus. Maecenas ut nisi quis diam sodales condimentum. Suspendisse et posuere nunc, ut cursus enim. Nullam rutrum orci ut sem auctor, condimentum molestie massa tristique." +
      "Ut dictum, lectus sit amet dapibus sollicitudin, dolor augue condimentum enim, a viverra ante magna sit amet eros. Suspendisse mollis tellus mauris, ut bibendum felis ultricies non. In tempor, neque a sollicitudin volutpat, sem augue eleifend ex, a tincidunt est purus at mi. Donec ullamcorper est risus, non imperdiet dolor ullamcorper vel. Maecenas venenatis vitae dolor ut suscipit. Etiam sem mauris, condimentum quis sapien vitae, dapibus dignissim est. Aliquam quis pharetra neque.";
   
  var data = [];
  for (var i = 0; i < str.length; i++)
    data.push(str.charCodeAt(i));
  return data;
};
